%%
%% Autogenerated by Thrift Compiler (0.9.2)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(flume_types).

-include("flume_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('ThriftFlumeEvent') ->
  {struct, [{1, {map, string, string}},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('ThriftFlumeEvent') ->
  {struct, [{1, required, {map, string, string}, 'headers', dict:new()},
          {2, required, string, 'body', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

