%%
%% Autogenerated by Thrift Compiler (0.9.2)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(thrift_source_protocol_thrift).
-behaviour(thrift_service).


-include("thrift_source_protocol_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% append(This, Event)
function_info('append', params_type) ->
  {struct, [{1, {struct, {'flume_types', 'ThriftFlumeEvent'}}}]}
;
function_info('append', reply_type) ->
  i32;
function_info('append', exceptions) ->
  {struct, []}
;
% appendBatch(This, Events)
function_info('appendBatch', params_type) ->
  {struct, [{1, {list, {struct, {'flume_types', 'ThriftFlumeEvent'}}}}]}
;
function_info('appendBatch', reply_type) ->
  i32;
function_info('appendBatch', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

